#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d        

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# reload fafety
killall sxhkd 
killall picom 
killall nitrogen 
killall dunst 
killall polybar 

# autostart
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --set-scaled /home/sky/data/background.jpg &
dunst &
polybar &

# rules
bspc rule -a Navigator desktop='^4'
bspc rule -a 'Lunar Client 1.8.9 (v2.15.7-2424)' desktop='^3'
bspc rule -a 'Lunar Client 1.21 (444d849/version/1-21_merge)' desktop='^3'
